"use client";

export default function LimitationsPage() {
  return (
    <div className="max-w-3xl">
      <h1 className="text-2xl font-bold text-gray-900 mb-6">
        About Patent Pulse
      </h1>

      <div className="space-y-8">
        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">
            What Patent Pulse Is
          </h2>
          <p className="text-gray-600 leading-relaxed">
            Patent Pulse is a patent intelligence tool that helps users discover
            trends, opportunities, and insights from patent filings. It uses
            publicly available patent data from the USPTO, EPO, and WIPO,
            combined with AI-generated summaries and analysis, to surface
            patterns and highlight patents worth attention.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">
            What Patent Pulse Is Not
          </h2>
          <p className="text-gray-600 leading-relaxed">
            Patent Pulse is <strong>not legal advice</strong>. It is not a
            substitute for professional patent counsel. The information provided
            should be treated as informational analysis, not as actionable legal
            guidance.
          </p>
        </section>

        <section className="bg-amber-50 border border-amber-200 rounded-lg p-5">
          <h2 className="text-lg font-semibold text-amber-800 mb-3">
            Important Limitations
          </h2>
          <ul className="space-y-3 text-sm text-amber-900">
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Expiry dates are estimates.</strong> Patent term depends
                on maintenance fees, patent term adjustment (PTA), patent term
                extension (PTE), terminal disclaimers, and other factors not
                fully captured in our data. Do not rely on estimated expiry dates
                without verification from official registers.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Legal status may be incomplete.</strong> Maintenance fee
                payment status, assignment history, litigation, and licensing
                information may not be current or available. A patent shown as
                &ldquo;expired&rdquo; may have active family members in other
                jurisdictions.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>AI-generated content is speculative.</strong> Summaries,
                opportunity narratives, &ldquo;Why Now&rdquo; analyses, and
                novel application suggestions are generated by language models.
                They may contain inaccuracies, omissions, or unfounded
                inferences. Treat them as starting points for further
                investigation, not conclusions.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Patent data may be delayed.</strong> Data is ingested
                weekly from official sources. There may be a lag between a patent
                event (filing, grant, lapse) and its appearance in Patent Pulse.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Coverage is not global.</strong> Patent Pulse currently
                focuses on USPTO, EPO, and WIPO data. Patents filed only in
                other offices (JPO, KIPO, CNIPA, etc.) may not appear.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Claims may be incomplete.</strong> Not all patents have
                full claims text available. Independent claim identification is
                heuristic-based.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-amber-500 mt-0.5 flex-shrink-0">▸</span>
              <span>
                <strong>Freedom to operate is not implied.</strong> An expired
                patent does not automatically mean an invention is free to use.
                Related patents, continuation applications, and active family
                members may still be in force.
              </span>
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">
            Data Sources
          </h2>
          <ul className="space-y-2 text-sm text-gray-600">
            <li className="flex items-start gap-2">
              <span className="text-gray-400">•</span>
              <span>
                <strong>USPTO</strong> — United States Patent and Trademark
                Office. Grants and applications via the Open Data Portal.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-gray-400">•</span>
              <span>
                <strong>EPO OPS</strong> — European Patent Office Open Patent
                Services. Publication data, family information, and abstracts.
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-gray-400">•</span>
              <span>
                <strong>WIPO PATENTSCOPE</strong> — World Intellectual Property
                Organization. PCT international applications.
              </span>
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-800 mb-2">
            Recommended Verification
          </h2>
          <p className="text-gray-600 leading-relaxed mb-3">
            Before acting on any patent information from Patent Pulse, we
            recommend verifying through official registers:
          </p>
          <ul className="space-y-2 text-sm">
            <li>
              <a
                href="https://patentcenter.uspto.gov/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-600 hover:text-primary-800 hover:underline"
              >
                USPTO Patent Center →
              </a>
            </li>
            <li>
              <a
                href="https://worldwide.espacenet.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-600 hover:text-primary-800 hover:underline"
              >
                Espacenet (EPO) →
              </a>
            </li>
            <li>
              <a
                href="https://patentscope.wipo.int/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-600 hover:text-primary-800 hover:underline"
              >
                WIPO PATENTSCOPE →
              </a>
            </li>
            <li>
              <a
                href="https://patents.google.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-600 hover:text-primary-800 hover:underline"
              >
                Google Patents →
              </a>
            </li>
          </ul>
        </section>

        <div className="border-t border-gray-200 pt-6">
          <p className="text-xs text-gray-400">
            Patent Pulse provides informational patent intelligence only. Nothing
            in this product constitutes legal advice. Consult a qualified patent
            attorney before making decisions based on patent data.
          </p>
        </div>
      </div>
    </div>
  );
}
