"""Content generation API — LinkedIn posts, content ideas, etc."""

from uuid import UUID

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import select

from app.ai.content_generator import generate_linkedin_post
from app.api.deps import DbSession
from app.core.ai_models import ContentDraft
from app.core.models import PatentPublication

router = APIRouter()


class GenerateLinkedInRequest(BaseModel):
    patent_id: str
    tone: str | None = None  # "analytical" | "curiosity" | "news"


class LinkedInResponse(BaseModel):
    status: str
    artifact_id: str
    draft_id: str
    post_markdown: str
    hook: str
    tone: str
    caveats: list[str]
    source_citation: str


def _build_source_citation(patent: PatentPublication) -> str:
    return (
        f"Patent {patent.publication_number} · "
        f"{patent.assignees[0] if patent.assignees else 'Unknown assignee'} · "
        f"Generated by Invention Index 8 AI. "
        f"Verify before publishing."
    )


async def _get_or_create_draft(
    db: DbSession,
    patent_id: UUID,
    content_text: str,
    artifact_id: UUID,
) -> ContentDraft:
    """Upsert a draft for (user_id='anonymous', source_id, content_type='linkedin_post').

    UPDATE existing row on regenerate; INSERT only if no prior draft exists.
    """
    result = await db.execute(
        select(ContentDraft)
        .where(
            ContentDraft.user_id == "anonymous",
            ContentDraft.source_id == patent_id,
            ContentDraft.content_type == "linkedin_post",
        )
        .order_by(ContentDraft.created_at.desc())
        .limit(1)
    )
    existing = result.scalar_one_or_none()

    if existing:
        existing.content_text = content_text
        existing.artifact_id = artifact_id
        # updated_at auto-updates via onupdate
        await db.commit()
        await db.refresh(existing)
        return existing
    else:
        draft = ContentDraft(
            user_id="anonymous",
            source_type="patent",
            source_id=patent_id,
            content_type="linkedin_post",
            content_text=content_text,
            status="draft",
            artifact_id=artifact_id,
        )
        db.add(draft)
        await db.commit()
        await db.refresh(draft)
        return draft


@router.post("/generate-linkedin", response_model=LinkedInResponse)
async def generate_linkedin(
    db: DbSession,
    body: GenerateLinkedInRequest,
) -> LinkedInResponse:
    """Generate a LinkedIn post for a patent. Cache-first via AI artifacts."""
    patent_id = UUID(body.patent_id)

    result = await db.execute(select(PatentPublication).where(PatentPublication.id == patent_id))
    patent = result.scalar_one_or_none()
    if not patent:
        raise HTTPException(status_code=404, detail="Patent not found")

    if not patent.title and not patent.abstract:
        raise HTTPException(
            status_code=400,
            detail="Patent has no title or abstract to generate content from",
        )

    data, artifact_id = await generate_linkedin_post(db, patent, run_id=None)

    draft = await _get_or_create_draft(db, patent_id, data["post_markdown"], artifact_id)

    return LinkedInResponse(
        status="success",
        artifact_id=str(artifact_id),
        draft_id=str(draft.id),
        post_markdown=data["post_markdown"],
        hook=data["hook"],
        tone=data["tone"],
        caveats=data["caveats"],
        source_citation=_build_source_citation(patent),
    )


@router.get("/drafts")
async def get_drafts(
    db: DbSession,
    patent_id: UUID = Query(..., description="Patent ID to fetch drafts for"),
) -> dict | None:
    """Return the latest LinkedIn post draft for a patent, or None (200 null body) if none."""
    result = await db.execute(
        select(ContentDraft)
        .where(
            ContentDraft.user_id == "anonymous",
            ContentDraft.source_id == patent_id,
            ContentDraft.content_type == "linkedin_post",
        )
        .order_by(ContentDraft.created_at.desc())
        .limit(1)
    )
    draft = result.scalar_one_or_none()

    if draft:
        # Look up the patent to build the source citation.
        patent_result = await db.execute(
            select(PatentPublication).where(PatentPublication.id == patent_id)
        )
        patent = patent_result.scalar_one_or_none()
        return {
            "draft_id": str(draft.id),
            "post_markdown": draft.content_text,
            "source_citation": _build_source_citation(patent) if patent else "",
            "status": draft.status,
            "created_at": draft.created_at.isoformat(),
            "updated_at": draft.updated_at.isoformat(),
        }
    return None
